baseurl = "https://djns.io/"
title = "Darren Jones"
author = "Darren Jones"
paginate = 10
theme = "arabica"

[permalinks]
  post = "/:title/"

[params]
    description = "PLATFORM ENGINEER, MUSICIAN, COMPOSER"
    replaceGoogleFonts = "fonts.loli.net"
    twitter = "dazjones"
